---
env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - airbnb-typescript-base
  - prettier
  - plugin:import/typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - './tsconfig.eslint.json'
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  import/no-extraneous-dependencies:
    'off'
    # - error
    # - devDependencies:
    #     - '**/*.test.ts'
    #     - '**/*.test.tsx'
    #     - targets/**
  import/prefer-default-export: 'off'
  '@typescript-eslint/no-unused-expressions': 'off'
  prettier/prettier: error
  arrow-body-style: 'off'
  prefer-arrow-callback: 'off'
  no-nested-ternary: 'off'
  no-restricted-syntax: 'off'
  no-await-in-loop: 'off'
  no-console:
    - 'warn'
    - allow: ['warn', 'error', 'info', 'debug']
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: ./tsconfig.eslint.json
